/*
 *  Copyright (C) 2009 Water Services Regulation Authority (Ofwat)
 *
 *  This program is free software; you can redistribute it and/or modify
 *  it under the terms of the GNU General Public License as published by
 *  the Free Software Foundation; either version 2 of the License, or
 *  (at your option) any later version.
 *
 *  This program is distributed in the hope that it will be useful,
 *  but WITHOUT ANY WARRANTY; without even the implied warranty of
 *  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *  GNU General Public License for more details.
 *
 *  You should have received a copy of the GNU General Public License along
 *  with this program; if not, write to the Free Software Foundation, Inc.,
 *  51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA.
 */
package uk.gov.ofwat.fountain.api.table;

import junit.framework.TestCase;
import org.junit.Assert;
import uk.gov.ofwat.fountain.api.report.CellType;
import uk.gov.ofwat.fountain.api.table.reader.SectionLayout;
import uk.gov.ofwat.fountain.domain.form.FormDisplayCell;
import uk.gov.ofwat.fountain.domain.form.FormEmptyCell;


public class TableWrapperRendererTest extends TestCase {

	private FormDisplayCell[][] formDisplayGrid;
	SectionLayout layout;

	public void setUp() {
		formDisplayGrid = getFormDisplayCell();
		layout = new SectionLayout(formDisplayGrid, formDisplayGrid.length, formDisplayGrid[0].length);
	}


	public void testFormDisplayCell() {

		String regressionString = "\n" +
				"       C       C C       C C\n" +
				"       C C C C   C C C C    \n" +
				" C C C                      \n" +
				" C C                        \n" +
				" R R R v v v v c v v v v c c\n" +
				" R R R v v v v c v v v v c c\n" +
				" R R R v v v v c v v v v c c\n" +
				" R R R v v v v c v v v v c c\n" +
				" R R R v v v v c v v v v c c\n" +
				" R R R v v v v c v v v v   c\n" +
				" R R R c c c c c c c c c c  ";
		Assert.assertEquals(regressionString, layout.printFormDisplayGrid());
	}


	public void testRowAndColOnEmptyCell() {
		FormDisplayCell formDisplayCell1 = formDisplayGrid[0][0];
		Assert.assertEquals(0, formDisplayCell1.getRow());
		Assert.assertEquals(0, formDisplayCell1.getColumn());

		FormDisplayCell formDisplayCell2 = formDisplayGrid[1][2];
		Assert.assertEquals(0, formDisplayCell2.getRow());
		Assert.assertEquals(0, formDisplayCell2.getColumn());

		layout.setRowAndColOnEmptyCells();

		Assert.assertEquals(0, formDisplayCell1.getRow());
		Assert.assertEquals(0, formDisplayCell1.getColumn());

		Assert.assertEquals(1, formDisplayCell2.getRow());
		Assert.assertEquals(2, formDisplayCell2.getColumn());
	}

	public void testSetSpansOnEmptyCell() {
		layout.setRowAndColOnEmptyCells();
		int row = 0;
		int col = 0;
		FormDisplayCell formDisplayCell = formDisplayGrid[row][col];
		Assert.assertEquals(0, formDisplayCell.getRowSpan());
		Assert.assertEquals(0, formDisplayCell.getColumnSpan());

		layout.setSpansOnEmptyCell(row, col, formDisplayCell);
		Assert.assertEquals(2, formDisplayCell.getRowSpan());
		Assert.assertEquals(3, formDisplayCell.getColumnSpan());
	}

	public void testSetSpansOnLoneEmptyCell() {
		layout.setRowAndColOnEmptyCells();
		int row = 9;
		int col = 12;
		FormDisplayCell formDisplayCell = formDisplayGrid[row][col];
		Assert.assertEquals(0, formDisplayCell.getRowSpan());
		Assert.assertEquals(0, formDisplayCell.getColumnSpan());

		layout.setSpansOnEmptyCell(row, col, formDisplayCell);
		Assert.assertEquals(1, formDisplayCell.getRowSpan());
		Assert.assertEquals(1, formDisplayCell.getColumnSpan());
	}

	public void testSetSpansOnEmptyLastCell() {
		layout.setRowAndColOnEmptyCells();
		int row = 10;
		int col = 13;
		FormDisplayCell formDisplayCell = formDisplayGrid[row][col];
		Assert.assertEquals(0, formDisplayCell.getRowSpan());
		Assert.assertEquals(0, formDisplayCell.getColumnSpan());

		layout.setSpansOnEmptyCell(row, col, formDisplayCell);
		Assert.assertEquals(1, formDisplayCell.getRowSpan());
		Assert.assertEquals(1, formDisplayCell.getColumnSpan());
	}

	public void testWholeSection() {
		layout.makeCellLayout();
	}


	public void testSpansOnColHeader() {
		FormDisplayCell formDisplayCell = formDisplayGrid[0][3];
		Assert.assertEquals(1, formDisplayCell.getRowSpan());
		Assert.assertEquals(4, formDisplayCell.getColumnSpan());

		formDisplayCell = formDisplayGrid[0][7];
		Assert.assertEquals(2, formDisplayCell.getRowSpan());
		Assert.assertEquals(1, formDisplayCell.getColumnSpan());
	}

	public void testMarkColSpannedCellsAsRedundent() {
		layout.setRowAndColOnEmptyCells();
		layout.initialiseCellLayout();

		int row = 0;
		int col = 3;
		FormDisplayCell formDisplayCell = formDisplayGrid[row][col];
		layout.markSpannedCellsAsRedundent(row, col, formDisplayCell);
		Assert.assertEquals("|C4 ", layout.setCellLayoutCode(row, col, formDisplayCell));
		Assert.assertEquals("|C4 ", layout.getCellLayout()[row][col]);
		Assert.assertEquals("|~  ", layout.getCellLayout()[row][col+1]);
		Assert.assertEquals("|~  ", layout.getCellLayout()[row][col+2]);
		Assert.assertEquals("|~  ", layout.getCellLayout()[row][col+3]);
	}

	public void testMarkRowSpannedCellsAsRedundent_startFromEmptyCell() {
		layout.setRowAndColOnEmptyCells();
		layout.initialiseCellLayout();

		int row = 0;
		int col = 0;
		FormDisplayCell formDisplayCell = formDisplayGrid[row][col];
		layout.setSpansOnEmptyCell(row, col, formDisplayCell);
		layout.markSpannedCellsAsRedundent(row, col, formDisplayCell);
		Assert.assertEquals("| 32", layout.setCellLayoutCode(row, col, formDisplayCell));
		Assert.assertEquals("| 32", layout.getCellLayout()[row][col]);
		Assert.assertEquals("|~  ", layout.getCellLayout()[row+1][col]);
	}

	public void testMarkColAndRowSpannedCellsAsRedundent_startFromEmptyCell() {
		layout.setRowAndColOnEmptyCells();
		layout.initialiseCellLayout();

		int row = 2;
		int col = 3;
		FormDisplayCell formDisplayCell = formDisplayGrid[row][col];
		layout.setSpansOnEmptyCell(row, col, formDisplayCell);
		layout.markSpannedCellsAsRedundent(row, col, formDisplayCell);
		Assert.assertEquals("| 112", layout.setCellLayoutCode(row, col, formDisplayCell));
		Assert.assertEquals("|~  ", layout.getCellLayout()[row+1][col]);
		for (int i=row; i<4; i++) {
			for (int j=col+1; j<13 ; j++) {
				Assert.assertEquals("|~  ", layout.getCellLayout()[i][j]);
			}
		}
	}

// | 32 |~   |~   |C4  |~   |~   |~   |C 2 |C4  |~   |~   |~   |C 2 |C 2
// |~   |~   |~   |C   |C   |C   |C   |~   |C   |C   |C   |C   |~   |~
// |C   |C   |C   | 112|~   |~   |~   |~   |~   |~   |~   |~   |~   |~
// |C   |C2  |~   |~   |~   |~   |~   |~   |~   |~   |~   |~   |~   |~
// |R   |R   |R   |v   |v   |v   |v   |c   |v   |v   |v   |v   |c   |c
// |R   |R   |R   |v   |v   |v   |v   |c   |v   |v   |v   |v   |c   |c
// |R   |R   |R   |v   |v   |v   |v   |c   |v   |v   |v   |v   |c   |c
// |R   |R   |R   |v   |v   |v   |v   |c   |v   |v   |v   |v   |c   |c
// |R   |R   |R   |v   |v   |v   |v   |c   |v   |v   |v   |v   |c   |c
// |R   |R   |R   |v   |v   |v   |v   |c   |v   |v   |v   |v   |c   |c
// |R   |R   |R   |c   |c   |c   |c   |c   |c   |c   |c   |c   |c   |c


//		layout.setRowAndColOnEmptyCells();
//		layout.initialiseCellLayout();
//		layout.markColSpannedCellsAsRedundent(rowCount, colCount, formDisplayCell);
//		layout.setCellLayoutCode(rowCount, colCount, formDisplayCell);




//		System.out.println("TEST: " + this.getClass().getCanonicalName() + ":testGetUser");
//		when(mockUser.getName()).thenReturn(userName);
//		when(mockAuditDao.create(isA(Audit.class))).thenReturn(auditId);
//
//		auditService.setAuditDao(mockAuditDao);
//		Audit audit = auditService.createAudit(comment, mockUser, mockCompany);
//
//		Assert.assertEquals(userName, audit.getUser().getName());
//
//		System.out.println("TEST: Done");


//	C       C C       C C
//	C C C C   C C C C
//	C C C
//	C C
//	R R R v v v v c v v v v c c
//	R R R v v v v c v v v v c c
//	R R R v v v v c v v v v c c
//	R R R v v v v c v v v v c c
//	R R R v v v v c v v v v c c
//	R R R v v v v c v v v v c c
//	R R R c c c c c c c c c c c

	private FormDisplayCell[][] getFormDisplayCell(){
		FormDisplayCell[][] formDisplayGrid = new FormDisplayCell[11][14];
		FormDisplayCell formDisplayCell = new FormEmptyCell();
		formDisplayCell.setColumn(0);
		formDisplayCell.setColumnSpan(0);
		formDisplayCell.setRow(0);
		formDisplayCell.setRowSpan(0);
		formDisplayCell.setCellType(CellType.EMPTY);
		formDisplayGrid[0][0] = formDisplayCell;
		formDisplayCell = new FormEmptyCell();
		formDisplayCell.setColumn(0);
		formDisplayCell.setColumnSpan(0);
		formDisplayCell.setRow(0);
		formDisplayCell.setRowSpan(0);
		formDisplayCell.setCellType(CellType.EMPTY);
		formDisplayGrid[0][1] = formDisplayCell;
		formDisplayCell = new FormEmptyCell();
		formDisplayCell.setColumn(0);
		formDisplayCell.setColumnSpan(0);
		formDisplayCell.setRow(0);
		formDisplayCell.setRowSpan(0);
		formDisplayCell.setCellType(CellType.EMPTY);
		formDisplayGrid[0][2] = formDisplayCell;
		formDisplayCell = new FormEmptyCell();
		formDisplayCell.setColumn(3);
		formDisplayCell.setColumnSpan(4);
		formDisplayCell.setRow(0);
		formDisplayCell.setRowSpan(1);
		formDisplayCell.setCellType(CellType.COL_HEADING);
		formDisplayGrid[0][3] = formDisplayCell;
		formDisplayCell = new FormEmptyCell();
		formDisplayCell.setColumn(0);
		formDisplayCell.setColumnSpan(0);
		formDisplayCell.setRow(0);
		formDisplayCell.setRowSpan(0);
		formDisplayCell.setCellType(CellType.EMPTY);
		formDisplayGrid[0][4] = formDisplayCell;
		formDisplayCell = new FormEmptyCell();
		formDisplayCell.setColumn(0);
		formDisplayCell.setColumnSpan(0);
		formDisplayCell.setRow(0);
		formDisplayCell.setRowSpan(0);
		formDisplayCell.setCellType(CellType.EMPTY);
		formDisplayGrid[0][5] = formDisplayCell;
		formDisplayCell = new FormEmptyCell();
		formDisplayCell.setColumn(0);
		formDisplayCell.setColumnSpan(0);
		formDisplayCell.setRow(0);
		formDisplayCell.setRowSpan(0);
		formDisplayCell.setCellType(CellType.EMPTY);
		formDisplayGrid[0][6] = formDisplayCell;
		formDisplayCell = new FormEmptyCell();
		formDisplayCell.setColumn(7);
		formDisplayCell.setColumnSpan(1);
		formDisplayCell.setRow(0);
		formDisplayCell.setRowSpan(2);
		formDisplayCell.setCellType(CellType.COL_HEADING);
		formDisplayGrid[0][7] = formDisplayCell;
		formDisplayCell = new FormEmptyCell();
		formDisplayCell.setColumn(8);
		formDisplayCell.setColumnSpan(4);
		formDisplayCell.setRow(0);
		formDisplayCell.setRowSpan(1);
		formDisplayCell.setCellType(CellType.COL_HEADING);
		formDisplayGrid[0][8] = formDisplayCell;
		formDisplayCell = new FormEmptyCell();
		formDisplayCell.setColumn(0);
		formDisplayCell.setColumnSpan(0);
		formDisplayCell.setRow(0);
		formDisplayCell.setRowSpan(0);
		formDisplayCell.setCellType(CellType.EMPTY);
		formDisplayGrid[0][9] = formDisplayCell;
		formDisplayCell = new FormEmptyCell();
		formDisplayCell.setColumn(0);
		formDisplayCell.setColumnSpan(0);
		formDisplayCell.setRow(0);
		formDisplayCell.setRowSpan(0);
		formDisplayCell.setCellType(CellType.EMPTY);
		formDisplayGrid[0][10] = formDisplayCell;
		formDisplayCell = new FormEmptyCell();
		formDisplayCell.setColumn(0);
		formDisplayCell.setColumnSpan(0);
		formDisplayCell.setRow(0);
		formDisplayCell.setRowSpan(0);
		formDisplayCell.setCellType(CellType.EMPTY);
		formDisplayGrid[0][11] = formDisplayCell;
		formDisplayCell = new FormEmptyCell();
		formDisplayCell.setColumn(12);
		formDisplayCell.setColumnSpan(1);
		formDisplayCell.setRow(0);
		formDisplayCell.setRowSpan(2);
		formDisplayCell.setCellType(CellType.COL_HEADING);
		formDisplayGrid[0][12] = formDisplayCell;
		formDisplayCell = new FormEmptyCell();
		formDisplayCell.setColumn(13);
		formDisplayCell.setColumnSpan(1);
		formDisplayCell.setRow(0);
		formDisplayCell.setRowSpan(2);
		formDisplayCell.setCellType(CellType.COL_HEADING);
		formDisplayGrid[0][13] = formDisplayCell;
		formDisplayCell = new FormEmptyCell();
		formDisplayCell.setColumn(0);
		formDisplayCell.setColumnSpan(0);
		formDisplayCell.setRow(0);
		formDisplayCell.setRowSpan(0);
		formDisplayCell.setCellType(CellType.EMPTY);
		formDisplayGrid[1][0] = formDisplayCell;
		formDisplayCell = new FormEmptyCell();
		formDisplayCell.setColumn(0);
		formDisplayCell.setColumnSpan(0);
		formDisplayCell.setRow(0);
		formDisplayCell.setRowSpan(0);
		formDisplayCell.setCellType(CellType.EMPTY);
		formDisplayGrid[1][1] = formDisplayCell;
		formDisplayCell = new FormEmptyCell();
		formDisplayCell.setColumn(0);
		formDisplayCell.setColumnSpan(0);
		formDisplayCell.setRow(0);
		formDisplayCell.setRowSpan(0);
		formDisplayCell.setCellType(CellType.EMPTY);
		formDisplayGrid[1][2] = formDisplayCell;
		formDisplayCell = new FormEmptyCell();
		formDisplayCell.setColumn(3);
		formDisplayCell.setColumnSpan(1);
		formDisplayCell.setRow(1);
		formDisplayCell.setRowSpan(1);
		formDisplayCell.setCellType(CellType.COL_HEADING);
		formDisplayGrid[1][3] = formDisplayCell;
		formDisplayCell = new FormEmptyCell();
		formDisplayCell.setColumn(4);
		formDisplayCell.setColumnSpan(1);
		formDisplayCell.setRow(1);
		formDisplayCell.setRowSpan(1);
		formDisplayCell.setCellType(CellType.COL_HEADING);
		formDisplayGrid[1][4] = formDisplayCell;
		formDisplayCell = new FormEmptyCell();
		formDisplayCell.setColumn(5);
		formDisplayCell.setColumnSpan(1);
		formDisplayCell.setRow(1);
		formDisplayCell.setRowSpan(1);
		formDisplayCell.setCellType(CellType.COL_HEADING);
		formDisplayGrid[1][5] = formDisplayCell;
		formDisplayCell = new FormEmptyCell();
		formDisplayCell.setColumn(6);
		formDisplayCell.setColumnSpan(1);
		formDisplayCell.setRow(1);
		formDisplayCell.setRowSpan(1);
		formDisplayCell.setCellType(CellType.COL_HEADING);
		formDisplayGrid[1][6] = formDisplayCell;
		formDisplayCell = new FormEmptyCell();
		formDisplayCell.setColumn(0);
		formDisplayCell.setColumnSpan(0);
		formDisplayCell.setRow(0);
		formDisplayCell.setRowSpan(0);
		formDisplayCell.setCellType(CellType.EMPTY);
		formDisplayGrid[1][7] = formDisplayCell;
		formDisplayCell = new FormEmptyCell();
		formDisplayCell.setColumn(8);
		formDisplayCell.setColumnSpan(1);
		formDisplayCell.setRow(1);
		formDisplayCell.setRowSpan(1);
		formDisplayCell.setCellType(CellType.COL_HEADING);
		formDisplayGrid[1][8] = formDisplayCell;
		formDisplayCell = new FormEmptyCell();
		formDisplayCell.setColumn(9);
		formDisplayCell.setColumnSpan(1);
		formDisplayCell.setRow(1);
		formDisplayCell.setRowSpan(1);
		formDisplayCell.setCellType(CellType.COL_HEADING);
		formDisplayGrid[1][9] = formDisplayCell;
		formDisplayCell = new FormEmptyCell();
		formDisplayCell.setColumn(10);
		formDisplayCell.setColumnSpan(1);
		formDisplayCell.setRow(1);
		formDisplayCell.setRowSpan(1);
		formDisplayCell.setCellType(CellType.COL_HEADING);
		formDisplayGrid[1][10] = formDisplayCell;
		formDisplayCell = new FormEmptyCell();
		formDisplayCell.setColumn(11);
		formDisplayCell.setColumnSpan(1);
		formDisplayCell.setRow(1);
		formDisplayCell.setRowSpan(1);
		formDisplayCell.setCellType(CellType.COL_HEADING);
		formDisplayGrid[1][11] = formDisplayCell;
		formDisplayCell = new FormEmptyCell();
		formDisplayCell.setColumn(0);
		formDisplayCell.setColumnSpan(0);
		formDisplayCell.setRow(0);
		formDisplayCell.setRowSpan(0);
		formDisplayCell.setCellType(CellType.EMPTY);
		formDisplayGrid[1][12] = formDisplayCell;
		formDisplayCell = new FormEmptyCell();
		formDisplayCell.setColumn(0);
		formDisplayCell.setColumnSpan(0);
		formDisplayCell.setRow(0);
		formDisplayCell.setRowSpan(0);
		formDisplayCell.setCellType(CellType.EMPTY);
		formDisplayGrid[1][13] = formDisplayCell;
		formDisplayCell = new FormEmptyCell();
		formDisplayCell.setColumn(0);
		formDisplayCell.setColumnSpan(1);
		formDisplayCell.setRow(2);
		formDisplayCell.setRowSpan(1);
		formDisplayCell.setCellType(CellType.COL_HEADING);
		formDisplayGrid[2][0] = formDisplayCell;
		formDisplayCell = new FormEmptyCell();
		formDisplayCell.setColumn(1);
		formDisplayCell.setColumnSpan(1);
		formDisplayCell.setRow(2);
		formDisplayCell.setRowSpan(1);
		formDisplayCell.setCellType(CellType.COL_HEADING);
		formDisplayGrid[2][1] = formDisplayCell;
		formDisplayCell = new FormEmptyCell();
		formDisplayCell.setColumn(2);
		formDisplayCell.setColumnSpan(1);
		formDisplayCell.setRow(2);
		formDisplayCell.setRowSpan(1);
		formDisplayCell.setCellType(CellType.COL_HEADING);
		formDisplayGrid[2][2] = formDisplayCell;
		formDisplayCell = new FormEmptyCell();
		formDisplayCell.setColumn(0);
		formDisplayCell.setColumnSpan(0);
		formDisplayCell.setRow(0);
		formDisplayCell.setRowSpan(0);
		formDisplayCell.setCellType(CellType.EMPTY);
		formDisplayGrid[2][3] = formDisplayCell;
		formDisplayCell = new FormEmptyCell();
		formDisplayCell.setColumn(0);
		formDisplayCell.setColumnSpan(0);
		formDisplayCell.setRow(0);
		formDisplayCell.setRowSpan(0);
		formDisplayCell.setCellType(CellType.EMPTY);
		formDisplayGrid[2][4] = formDisplayCell;
		formDisplayCell = new FormEmptyCell();
		formDisplayCell.setColumn(0);
		formDisplayCell.setColumnSpan(0);
		formDisplayCell.setRow(0);
		formDisplayCell.setRowSpan(0);
		formDisplayCell.setCellType(CellType.EMPTY);
		formDisplayGrid[2][5] = formDisplayCell;
		formDisplayCell = new FormEmptyCell();
		formDisplayCell.setColumn(0);
		formDisplayCell.setColumnSpan(0);
		formDisplayCell.setRow(0);
		formDisplayCell.setRowSpan(0);
		formDisplayCell.setCellType(CellType.EMPTY);
		formDisplayGrid[2][6] = formDisplayCell;
		formDisplayCell = new FormEmptyCell();
		formDisplayCell.setColumn(0);
		formDisplayCell.setColumnSpan(0);
		formDisplayCell.setRow(0);
		formDisplayCell.setRowSpan(0);
		formDisplayCell.setCellType(CellType.EMPTY);
		formDisplayGrid[2][7] = formDisplayCell;
		formDisplayCell = new FormEmptyCell();
		formDisplayCell.setColumn(0);
		formDisplayCell.setColumnSpan(0);
		formDisplayCell.setRow(0);
		formDisplayCell.setRowSpan(0);
		formDisplayCell.setCellType(CellType.EMPTY);
		formDisplayGrid[2][8] = formDisplayCell;
		formDisplayCell = new FormEmptyCell();
		formDisplayCell.setColumn(0);
		formDisplayCell.setColumnSpan(0);
		formDisplayCell.setRow(0);
		formDisplayCell.setRowSpan(0);
		formDisplayCell.setCellType(CellType.EMPTY);
		formDisplayGrid[2][9] = formDisplayCell;
		formDisplayCell = new FormEmptyCell();
		formDisplayCell.setColumn(0);
		formDisplayCell.setColumnSpan(0);
		formDisplayCell.setRow(0);
		formDisplayCell.setRowSpan(0);
		formDisplayCell.setCellType(CellType.EMPTY);
		formDisplayGrid[2][10] = formDisplayCell;
		formDisplayCell = new FormEmptyCell();
		formDisplayCell.setColumn(0);
		formDisplayCell.setColumnSpan(0);
		formDisplayCell.setRow(0);
		formDisplayCell.setRowSpan(0);
		formDisplayCell.setCellType(CellType.EMPTY);
		formDisplayGrid[2][11] = formDisplayCell;
		formDisplayCell = new FormEmptyCell();
		formDisplayCell.setColumn(0);
		formDisplayCell.setColumnSpan(0);
		formDisplayCell.setRow(0);
		formDisplayCell.setRowSpan(0);
		formDisplayCell.setCellType(CellType.EMPTY);
		formDisplayGrid[2][12] = formDisplayCell;
		formDisplayCell = new FormEmptyCell();
		formDisplayCell.setColumn(0);
		formDisplayCell.setColumnSpan(0);
		formDisplayCell.setRow(0);
		formDisplayCell.setRowSpan(0);
		formDisplayCell.setCellType(CellType.EMPTY);
		formDisplayGrid[2][13] = formDisplayCell;
		formDisplayCell = new FormEmptyCell();
		formDisplayCell.setColumn(0);
		formDisplayCell.setColumnSpan(1);
		formDisplayCell.setRow(3);
		formDisplayCell.setRowSpan(1);
		formDisplayCell.setCellType(CellType.COL_HEADING);
		formDisplayGrid[3][0] = formDisplayCell;
		formDisplayCell = new FormEmptyCell();
		formDisplayCell.setColumn(1);
		formDisplayCell.setColumnSpan(2);
		formDisplayCell.setRow(3);
		formDisplayCell.setRowSpan(1);
		formDisplayCell.setCellType(CellType.COL_HEADING);
		formDisplayGrid[3][1] = formDisplayCell;
		formDisplayCell = new FormEmptyCell();
		formDisplayCell.setColumn(0);
		formDisplayCell.setColumnSpan(0);
		formDisplayCell.setRow(0);
		formDisplayCell.setRowSpan(0);
		formDisplayCell.setCellType(CellType.EMPTY);
		formDisplayGrid[3][2] = formDisplayCell;
		formDisplayCell = new FormEmptyCell();
		formDisplayCell.setColumn(0);
		formDisplayCell.setColumnSpan(0);
		formDisplayCell.setRow(0);
		formDisplayCell.setRowSpan(0);
		formDisplayCell.setCellType(CellType.EMPTY);
		formDisplayGrid[3][3] = formDisplayCell;
		formDisplayCell = new FormEmptyCell();
		formDisplayCell.setColumn(0);
		formDisplayCell.setColumnSpan(0);
		formDisplayCell.setRow(0);
		formDisplayCell.setRowSpan(0);
		formDisplayCell.setCellType(CellType.EMPTY);
		formDisplayGrid[3][4] = formDisplayCell;
		formDisplayCell = new FormEmptyCell();
		formDisplayCell.setColumn(0);
		formDisplayCell.setColumnSpan(0);
		formDisplayCell.setRow(0);
		formDisplayCell.setRowSpan(0);
		formDisplayCell.setCellType(CellType.EMPTY);
		formDisplayGrid[3][5] = formDisplayCell;
		formDisplayCell = new FormEmptyCell();
		formDisplayCell.setColumn(0);
		formDisplayCell.setColumnSpan(0);
		formDisplayCell.setRow(0);
		formDisplayCell.setRowSpan(0);
		formDisplayCell.setCellType(CellType.EMPTY);
		formDisplayGrid[3][6] = formDisplayCell;
		formDisplayCell = new FormEmptyCell();
		formDisplayCell.setColumn(0);
		formDisplayCell.setColumnSpan(0);
		formDisplayCell.setRow(0);
		formDisplayCell.setRowSpan(0);
		formDisplayCell.setCellType(CellType.EMPTY);
		formDisplayGrid[3][7] = formDisplayCell;
		formDisplayCell = new FormEmptyCell();
		formDisplayCell.setColumn(0);
		formDisplayCell.setColumnSpan(0);
		formDisplayCell.setRow(0);
		formDisplayCell.setRowSpan(0);
		formDisplayCell.setCellType(CellType.EMPTY);
		formDisplayGrid[3][8] = formDisplayCell;
		formDisplayCell = new FormEmptyCell();
		formDisplayCell.setColumn(0);
		formDisplayCell.setColumnSpan(0);
		formDisplayCell.setRow(0);
		formDisplayCell.setRowSpan(0);
		formDisplayCell.setCellType(CellType.EMPTY);
		formDisplayGrid[3][9] = formDisplayCell;
		formDisplayCell = new FormEmptyCell();
		formDisplayCell.setColumn(0);
		formDisplayCell.setColumnSpan(0);
		formDisplayCell.setRow(0);
		formDisplayCell.setRowSpan(0);
		formDisplayCell.setCellType(CellType.EMPTY);
		formDisplayGrid[3][10] = formDisplayCell;
		formDisplayCell = new FormEmptyCell();
		formDisplayCell.setColumn(0);
		formDisplayCell.setColumnSpan(0);
		formDisplayCell.setRow(0);
		formDisplayCell.setRowSpan(0);
		formDisplayCell.setCellType(CellType.EMPTY);
		formDisplayGrid[3][11] = formDisplayCell;
		formDisplayCell = new FormEmptyCell();
		formDisplayCell.setColumn(0);
		formDisplayCell.setColumnSpan(0);
		formDisplayCell.setRow(0);
		formDisplayCell.setRowSpan(0);
		formDisplayCell.setCellType(CellType.EMPTY);
		formDisplayGrid[3][12] = formDisplayCell;
		formDisplayCell = new FormEmptyCell();
		formDisplayCell.setColumn(0);
		formDisplayCell.setColumnSpan(0);
		formDisplayCell.setRow(0);
		formDisplayCell.setRowSpan(0);
		formDisplayCell.setCellType(CellType.EMPTY);
		formDisplayGrid[3][13] = formDisplayCell;
		formDisplayCell = new FormEmptyCell();
		formDisplayCell.setColumn(0);
		formDisplayCell.setColumnSpan(1);
		formDisplayCell.setRow(4);
		formDisplayCell.setRowSpan(1);
		formDisplayCell.setCellType(CellType.ROW_HEADING);
		formDisplayGrid[4][0] = formDisplayCell;
		formDisplayCell = new FormEmptyCell();
		formDisplayCell.setColumn(1);
		formDisplayCell.setColumnSpan(1);
		formDisplayCell.setRow(4);
		formDisplayCell.setRowSpan(1);
		formDisplayCell.setCellType(CellType.ROW_HEADING);
		formDisplayGrid[4][1] = formDisplayCell;
		formDisplayCell = new FormEmptyCell();
		formDisplayCell.setColumn(2);
		formDisplayCell.setColumnSpan(1);
		formDisplayCell.setRow(4);
		formDisplayCell.setRowSpan(1);
		formDisplayCell.setCellType(CellType.ROW_HEADING);
		formDisplayGrid[4][2] = formDisplayCell;
		formDisplayCell = new FormEmptyCell();
		formDisplayCell.setColumn(3);
		formDisplayCell.setColumnSpan(1);
		formDisplayCell.setRow(4);
		formDisplayCell.setRowSpan(1);
		formDisplayCell.setCellType(CellType.INPUT);
		formDisplayGrid[4][3] = formDisplayCell;
		formDisplayCell = new FormEmptyCell();
		formDisplayCell.setColumn(4);
		formDisplayCell.setColumnSpan(1);
		formDisplayCell.setRow(4);
		formDisplayCell.setRowSpan(1);
		formDisplayCell.setCellType(CellType.INPUT);
		formDisplayGrid[4][4] = formDisplayCell;
		formDisplayCell = new FormEmptyCell();
		formDisplayCell.setColumn(5);
		formDisplayCell.setColumnSpan(1);
		formDisplayCell.setRow(4);
		formDisplayCell.setRowSpan(1);
		formDisplayCell.setCellType(CellType.INPUT);
		formDisplayGrid[4][5] = formDisplayCell;
		formDisplayCell = new FormEmptyCell();
		formDisplayCell.setColumn(6);
		formDisplayCell.setColumnSpan(1);
		formDisplayCell.setRow(4);
		formDisplayCell.setRowSpan(1);
		formDisplayCell.setCellType(CellType.INPUT);
		formDisplayGrid[4][6] = formDisplayCell;
		formDisplayCell = new FormEmptyCell();
		formDisplayCell.setColumn(7);
		formDisplayCell.setColumnSpan(1);
		formDisplayCell.setRow(4);
		formDisplayCell.setRowSpan(1);
		formDisplayCell.setCellType(CellType.CALC);
		formDisplayGrid[4][7] = formDisplayCell;
		formDisplayCell = new FormEmptyCell();
		formDisplayCell.setColumn(8);
		formDisplayCell.setColumnSpan(1);
		formDisplayCell.setRow(4);
		formDisplayCell.setRowSpan(1);
		formDisplayCell.setCellType(CellType.INPUT);
		formDisplayGrid[4][8] = formDisplayCell;
		formDisplayCell = new FormEmptyCell();
		formDisplayCell.setColumn(9);
		formDisplayCell.setColumnSpan(1);
		formDisplayCell.setRow(4);
		formDisplayCell.setRowSpan(1);
		formDisplayCell.setCellType(CellType.INPUT);
		formDisplayGrid[4][9] = formDisplayCell;
		formDisplayCell = new FormEmptyCell();
		formDisplayCell.setColumn(10);
		formDisplayCell.setColumnSpan(1);
		formDisplayCell.setRow(4);
		formDisplayCell.setRowSpan(1);
		formDisplayCell.setCellType(CellType.INPUT);
		formDisplayGrid[4][10] = formDisplayCell;
		formDisplayCell = new FormEmptyCell();
		formDisplayCell.setColumn(11);
		formDisplayCell.setColumnSpan(1);
		formDisplayCell.setRow(4);
		formDisplayCell.setRowSpan(1);
		formDisplayCell.setCellType(CellType.INPUT);
		formDisplayGrid[4][11] = formDisplayCell;
		formDisplayCell = new FormEmptyCell();
		formDisplayCell.setColumn(12);
		formDisplayCell.setColumnSpan(1);
		formDisplayCell.setRow(4);
		formDisplayCell.setRowSpan(1);
		formDisplayCell.setCellType(CellType.CALC);
		formDisplayGrid[4][12] = formDisplayCell;
		formDisplayCell = new FormEmptyCell();
		formDisplayCell.setColumn(13);
		formDisplayCell.setColumnSpan(1);
		formDisplayCell.setRow(4);
		formDisplayCell.setRowSpan(1);
		formDisplayCell.setCellType(CellType.CALC);
		formDisplayGrid[4][13] = formDisplayCell;
		formDisplayCell = new FormEmptyCell();
		formDisplayCell.setColumn(0);
		formDisplayCell.setColumnSpan(1);
		formDisplayCell.setRow(5);
		formDisplayCell.setRowSpan(1);
		formDisplayCell.setCellType(CellType.ROW_HEADING);
		formDisplayGrid[5][0] = formDisplayCell;
		formDisplayCell = new FormEmptyCell();
		formDisplayCell.setColumn(1);
		formDisplayCell.setColumnSpan(1);
		formDisplayCell.setRow(5);
		formDisplayCell.setRowSpan(1);
		formDisplayCell.setCellType(CellType.ROW_HEADING);
		formDisplayGrid[5][1] = formDisplayCell;
		formDisplayCell = new FormEmptyCell();
		formDisplayCell.setColumn(2);
		formDisplayCell.setColumnSpan(1);
		formDisplayCell.setRow(5);
		formDisplayCell.setRowSpan(1);
		formDisplayCell.setCellType(CellType.ROW_HEADING);
		formDisplayGrid[5][2] = formDisplayCell;
		formDisplayCell = new FormEmptyCell();
		formDisplayCell.setColumn(3);
		formDisplayCell.setColumnSpan(1);
		formDisplayCell.setRow(5);
		formDisplayCell.setRowSpan(1);
		formDisplayCell.setCellType(CellType.INPUT);
		formDisplayGrid[5][3] = formDisplayCell;
		formDisplayCell = new FormEmptyCell();
		formDisplayCell.setColumn(4);
		formDisplayCell.setColumnSpan(1);
		formDisplayCell.setRow(5);
		formDisplayCell.setRowSpan(1);
		formDisplayCell.setCellType(CellType.INPUT);
		formDisplayGrid[5][4] = formDisplayCell;
		formDisplayCell = new FormEmptyCell();
		formDisplayCell.setColumn(5);
		formDisplayCell.setColumnSpan(1);
		formDisplayCell.setRow(5);
		formDisplayCell.setRowSpan(1);
		formDisplayCell.setCellType(CellType.INPUT);
		formDisplayGrid[5][5] = formDisplayCell;
		formDisplayCell = new FormEmptyCell();
		formDisplayCell.setColumn(6);
		formDisplayCell.setColumnSpan(1);
		formDisplayCell.setRow(5);
		formDisplayCell.setRowSpan(1);
		formDisplayCell.setCellType(CellType.INPUT);
		formDisplayGrid[5][6] = formDisplayCell;
		formDisplayCell = new FormEmptyCell();
		formDisplayCell.setColumn(7);
		formDisplayCell.setColumnSpan(1);
		formDisplayCell.setRow(5);
		formDisplayCell.setRowSpan(1);
		formDisplayCell.setCellType(CellType.CALC);
		formDisplayGrid[5][7] = formDisplayCell;
		formDisplayCell = new FormEmptyCell();
		formDisplayCell.setColumn(8);
		formDisplayCell.setColumnSpan(1);
		formDisplayCell.setRow(5);
		formDisplayCell.setRowSpan(1);
		formDisplayCell.setCellType(CellType.INPUT);
		formDisplayGrid[5][8] = formDisplayCell;
		formDisplayCell = new FormEmptyCell();
		formDisplayCell.setColumn(9);
		formDisplayCell.setColumnSpan(1);
		formDisplayCell.setRow(5);
		formDisplayCell.setRowSpan(1);
		formDisplayCell.setCellType(CellType.INPUT);
		formDisplayGrid[5][9] = formDisplayCell;
		formDisplayCell = new FormEmptyCell();
		formDisplayCell.setColumn(10);
		formDisplayCell.setColumnSpan(1);
		formDisplayCell.setRow(5);
		formDisplayCell.setRowSpan(1);
		formDisplayCell.setCellType(CellType.INPUT);
		formDisplayGrid[5][10] = formDisplayCell;
		formDisplayCell = new FormEmptyCell();
		formDisplayCell.setColumn(11);
		formDisplayCell.setColumnSpan(1);
		formDisplayCell.setRow(5);
		formDisplayCell.setRowSpan(1);
		formDisplayCell.setCellType(CellType.INPUT);
		formDisplayGrid[5][11] = formDisplayCell;
		formDisplayCell = new FormEmptyCell();
		formDisplayCell.setColumn(12);
		formDisplayCell.setColumnSpan(1);
		formDisplayCell.setRow(5);
		formDisplayCell.setRowSpan(1);
		formDisplayCell.setCellType(CellType.CALC);
		formDisplayGrid[5][12] = formDisplayCell;
		formDisplayCell = new FormEmptyCell();
		formDisplayCell.setColumn(13);
		formDisplayCell.setColumnSpan(1);
		formDisplayCell.setRow(5);
		formDisplayCell.setRowSpan(1);
		formDisplayCell.setCellType(CellType.CALC);
		formDisplayGrid[5][13] = formDisplayCell;
		formDisplayCell = new FormEmptyCell();
		formDisplayCell.setColumn(0);
		formDisplayCell.setColumnSpan(1);
		formDisplayCell.setRow(6);
		formDisplayCell.setRowSpan(1);
		formDisplayCell.setCellType(CellType.ROW_HEADING);
		formDisplayGrid[6][0] = formDisplayCell;
		formDisplayCell = new FormEmptyCell();
		formDisplayCell.setColumn(1);
		formDisplayCell.setColumnSpan(1);
		formDisplayCell.setRow(6);
		formDisplayCell.setRowSpan(1);
		formDisplayCell.setCellType(CellType.ROW_HEADING);
		formDisplayGrid[6][1] = formDisplayCell;
		formDisplayCell = new FormEmptyCell();
		formDisplayCell.setColumn(2);
		formDisplayCell.setColumnSpan(1);
		formDisplayCell.setRow(6);
		formDisplayCell.setRowSpan(1);
		formDisplayCell.setCellType(CellType.ROW_HEADING);
		formDisplayGrid[6][2] = formDisplayCell;
		formDisplayCell = new FormEmptyCell();
		formDisplayCell.setColumn(3);
		formDisplayCell.setColumnSpan(1);
		formDisplayCell.setRow(6);
		formDisplayCell.setRowSpan(1);
		formDisplayCell.setCellType(CellType.INPUT);
		formDisplayGrid[6][3] = formDisplayCell;
		formDisplayCell = new FormEmptyCell();
		formDisplayCell.setColumn(4);
		formDisplayCell.setColumnSpan(1);
		formDisplayCell.setRow(6);
		formDisplayCell.setRowSpan(1);
		formDisplayCell.setCellType(CellType.INPUT);
		formDisplayGrid[6][4] = formDisplayCell;
		formDisplayCell = new FormEmptyCell();
		formDisplayCell.setColumn(5);
		formDisplayCell.setColumnSpan(1);
		formDisplayCell.setRow(6);
		formDisplayCell.setRowSpan(1);
		formDisplayCell.setCellType(CellType.INPUT);
		formDisplayGrid[6][5] = formDisplayCell;
		formDisplayCell = new FormEmptyCell();
		formDisplayCell.setColumn(6);
		formDisplayCell.setColumnSpan(1);
		formDisplayCell.setRow(6);
		formDisplayCell.setRowSpan(1);
		formDisplayCell.setCellType(CellType.INPUT);
		formDisplayGrid[6][6] = formDisplayCell;
		formDisplayCell = new FormEmptyCell();
		formDisplayCell.setColumn(7);
		formDisplayCell.setColumnSpan(1);
		formDisplayCell.setRow(6);
		formDisplayCell.setRowSpan(1);
		formDisplayCell.setCellType(CellType.CALC);
		formDisplayGrid[6][7] = formDisplayCell;
		formDisplayCell = new FormEmptyCell();
		formDisplayCell.setColumn(8);
		formDisplayCell.setColumnSpan(1);
		formDisplayCell.setRow(6);
		formDisplayCell.setRowSpan(1);
		formDisplayCell.setCellType(CellType.INPUT);
		formDisplayGrid[6][8] = formDisplayCell;
		formDisplayCell = new FormEmptyCell();
		formDisplayCell.setColumn(9);
		formDisplayCell.setColumnSpan(1);
		formDisplayCell.setRow(6);
		formDisplayCell.setRowSpan(1);
		formDisplayCell.setCellType(CellType.INPUT);
		formDisplayGrid[6][9] = formDisplayCell;
		formDisplayCell = new FormEmptyCell();
		formDisplayCell.setColumn(10);
		formDisplayCell.setColumnSpan(1);
		formDisplayCell.setRow(6);
		formDisplayCell.setRowSpan(1);
		formDisplayCell.setCellType(CellType.INPUT);
		formDisplayGrid[6][10] = formDisplayCell;
		formDisplayCell = new FormEmptyCell();
		formDisplayCell.setColumn(11);
		formDisplayCell.setColumnSpan(1);
		formDisplayCell.setRow(6);
		formDisplayCell.setRowSpan(1);
		formDisplayCell.setCellType(CellType.INPUT);
		formDisplayGrid[6][11] = formDisplayCell;
		formDisplayCell = new FormEmptyCell();
		formDisplayCell.setColumn(12);
		formDisplayCell.setColumnSpan(1);
		formDisplayCell.setRow(6);
		formDisplayCell.setRowSpan(1);
		formDisplayCell.setCellType(CellType.CALC);
		formDisplayGrid[6][12] = formDisplayCell;
		formDisplayCell = new FormEmptyCell();
		formDisplayCell.setColumn(13);
		formDisplayCell.setColumnSpan(1);
		formDisplayCell.setRow(6);
		formDisplayCell.setRowSpan(1);
		formDisplayCell.setCellType(CellType.CALC);
		formDisplayGrid[6][13] = formDisplayCell;
		formDisplayCell = new FormEmptyCell();
		formDisplayCell.setColumn(0);
		formDisplayCell.setColumnSpan(1);
		formDisplayCell.setRow(7);
		formDisplayCell.setRowSpan(1);
		formDisplayCell.setCellType(CellType.ROW_HEADING);
		formDisplayGrid[7][0] = formDisplayCell;
		formDisplayCell = new FormEmptyCell();
		formDisplayCell.setColumn(1);
		formDisplayCell.setColumnSpan(1);
		formDisplayCell.setRow(7);
		formDisplayCell.setRowSpan(1);
		formDisplayCell.setCellType(CellType.ROW_HEADING);
		formDisplayGrid[7][1] = formDisplayCell;
		formDisplayCell = new FormEmptyCell();
		formDisplayCell.setColumn(2);
		formDisplayCell.setColumnSpan(1);
		formDisplayCell.setRow(7);
		formDisplayCell.setRowSpan(1);
		formDisplayCell.setCellType(CellType.ROW_HEADING);
		formDisplayGrid[7][2] = formDisplayCell;
		formDisplayCell = new FormEmptyCell();
		formDisplayCell.setColumn(3);
		formDisplayCell.setColumnSpan(1);
		formDisplayCell.setRow(7);
		formDisplayCell.setRowSpan(1);
		formDisplayCell.setCellType(CellType.INPUT);
		formDisplayGrid[7][3] = formDisplayCell;
		formDisplayCell = new FormEmptyCell();
		formDisplayCell.setColumn(4);
		formDisplayCell.setColumnSpan(1);
		formDisplayCell.setRow(7);
		formDisplayCell.setRowSpan(1);
		formDisplayCell.setCellType(CellType.INPUT);
		formDisplayGrid[7][4] = formDisplayCell;
		formDisplayCell = new FormEmptyCell();
		formDisplayCell.setColumn(5);
		formDisplayCell.setColumnSpan(1);
		formDisplayCell.setRow(7);
		formDisplayCell.setRowSpan(1);
		formDisplayCell.setCellType(CellType.INPUT);
		formDisplayGrid[7][5] = formDisplayCell;
		formDisplayCell = new FormEmptyCell();
		formDisplayCell.setColumn(6);
		formDisplayCell.setColumnSpan(1);
		formDisplayCell.setRow(7);
		formDisplayCell.setRowSpan(1);
		formDisplayCell.setCellType(CellType.INPUT);
		formDisplayGrid[7][6] = formDisplayCell;
		formDisplayCell = new FormEmptyCell();
		formDisplayCell.setColumn(7);
		formDisplayCell.setColumnSpan(1);
		formDisplayCell.setRow(7);
		formDisplayCell.setRowSpan(1);
		formDisplayCell.setCellType(CellType.CALC);
		formDisplayGrid[7][7] = formDisplayCell;
		formDisplayCell = new FormEmptyCell();
		formDisplayCell.setColumn(8);
		formDisplayCell.setColumnSpan(1);
		formDisplayCell.setRow(7);
		formDisplayCell.setRowSpan(1);
		formDisplayCell.setCellType(CellType.INPUT);
		formDisplayGrid[7][8] = formDisplayCell;
		formDisplayCell = new FormEmptyCell();
		formDisplayCell.setColumn(9);
		formDisplayCell.setColumnSpan(1);
		formDisplayCell.setRow(7);
		formDisplayCell.setRowSpan(1);
		formDisplayCell.setCellType(CellType.INPUT);
		formDisplayGrid[7][9] = formDisplayCell;
		formDisplayCell = new FormEmptyCell();
		formDisplayCell.setColumn(10);
		formDisplayCell.setColumnSpan(1);
		formDisplayCell.setRow(7);
		formDisplayCell.setRowSpan(1);
		formDisplayCell.setCellType(CellType.INPUT);
		formDisplayGrid[7][10] = formDisplayCell;
		formDisplayCell = new FormEmptyCell();
		formDisplayCell.setColumn(11);
		formDisplayCell.setColumnSpan(1);
		formDisplayCell.setRow(7);
		formDisplayCell.setRowSpan(1);
		formDisplayCell.setCellType(CellType.INPUT);
		formDisplayGrid[7][11] = formDisplayCell;
		formDisplayCell = new FormEmptyCell();
		formDisplayCell.setColumn(12);
		formDisplayCell.setColumnSpan(1);
		formDisplayCell.setRow(7);
		formDisplayCell.setRowSpan(1);
		formDisplayCell.setCellType(CellType.CALC);
		formDisplayGrid[7][12] = formDisplayCell;
		formDisplayCell = new FormEmptyCell();
		formDisplayCell.setColumn(13);
		formDisplayCell.setColumnSpan(1);
		formDisplayCell.setRow(7);
		formDisplayCell.setRowSpan(1);
		formDisplayCell.setCellType(CellType.CALC);
		formDisplayGrid[7][13] = formDisplayCell;
		formDisplayCell = new FormEmptyCell();
		formDisplayCell.setColumn(0);
		formDisplayCell.setColumnSpan(1);
		formDisplayCell.setRow(8);
		formDisplayCell.setRowSpan(1);
		formDisplayCell.setCellType(CellType.ROW_HEADING);
		formDisplayGrid[8][0] = formDisplayCell;
		formDisplayCell = new FormEmptyCell();
		formDisplayCell.setColumn(1);
		formDisplayCell.setColumnSpan(1);
		formDisplayCell.setRow(8);
		formDisplayCell.setRowSpan(1);
		formDisplayCell.setCellType(CellType.ROW_HEADING);
		formDisplayGrid[8][1] = formDisplayCell;
		formDisplayCell = new FormEmptyCell();
		formDisplayCell.setColumn(2);
		formDisplayCell.setColumnSpan(1);
		formDisplayCell.setRow(8);
		formDisplayCell.setRowSpan(1);
		formDisplayCell.setCellType(CellType.ROW_HEADING);
		formDisplayGrid[8][2] = formDisplayCell;
		formDisplayCell = new FormEmptyCell();
		formDisplayCell.setColumn(3);
		formDisplayCell.setColumnSpan(1);
		formDisplayCell.setRow(8);
		formDisplayCell.setRowSpan(1);
		formDisplayCell.setCellType(CellType.INPUT);
		formDisplayGrid[8][3] = formDisplayCell;
		formDisplayCell = new FormEmptyCell();
		formDisplayCell.setColumn(4);
		formDisplayCell.setColumnSpan(1);
		formDisplayCell.setRow(8);
		formDisplayCell.setRowSpan(1);
		formDisplayCell.setCellType(CellType.INPUT);
		formDisplayGrid[8][4] = formDisplayCell;
		formDisplayCell = new FormEmptyCell();
		formDisplayCell.setColumn(5);
		formDisplayCell.setColumnSpan(1);
		formDisplayCell.setRow(8);
		formDisplayCell.setRowSpan(1);
		formDisplayCell.setCellType(CellType.INPUT);
		formDisplayGrid[8][5] = formDisplayCell;
		formDisplayCell = new FormEmptyCell();
		formDisplayCell.setColumn(6);
		formDisplayCell.setColumnSpan(1);
		formDisplayCell.setRow(8);
		formDisplayCell.setRowSpan(1);
		formDisplayCell.setCellType(CellType.INPUT);
		formDisplayGrid[8][6] = formDisplayCell;
		formDisplayCell = new FormEmptyCell();
		formDisplayCell.setColumn(7);
		formDisplayCell.setColumnSpan(1);
		formDisplayCell.setRow(8);
		formDisplayCell.setRowSpan(1);
		formDisplayCell.setCellType(CellType.CALC);
		formDisplayGrid[8][7] = formDisplayCell;
		formDisplayCell = new FormEmptyCell();
		formDisplayCell.setColumn(8);
		formDisplayCell.setColumnSpan(1);
		formDisplayCell.setRow(8);
		formDisplayCell.setRowSpan(1);
		formDisplayCell.setCellType(CellType.INPUT);
		formDisplayGrid[8][8] = formDisplayCell;
		formDisplayCell = new FormEmptyCell();
		formDisplayCell.setColumn(9);
		formDisplayCell.setColumnSpan(1);
		formDisplayCell.setRow(8);
		formDisplayCell.setRowSpan(1);
		formDisplayCell.setCellType(CellType.INPUT);
		formDisplayGrid[8][9] = formDisplayCell;
		formDisplayCell = new FormEmptyCell();
		formDisplayCell.setColumn(10);
		formDisplayCell.setColumnSpan(1);
		formDisplayCell.setRow(8);
		formDisplayCell.setRowSpan(1);
		formDisplayCell.setCellType(CellType.INPUT);
		formDisplayGrid[8][10] = formDisplayCell;
		formDisplayCell = new FormEmptyCell();
		formDisplayCell.setColumn(11);
		formDisplayCell.setColumnSpan(1);
		formDisplayCell.setRow(8);
		formDisplayCell.setRowSpan(1);
		formDisplayCell.setCellType(CellType.INPUT);
		formDisplayGrid[8][11] = formDisplayCell;
		formDisplayCell = new FormEmptyCell();
		formDisplayCell.setColumn(12);
		formDisplayCell.setColumnSpan(1);
		formDisplayCell.setRow(8);
		formDisplayCell.setRowSpan(1);
		formDisplayCell.setCellType(CellType.CALC);
		formDisplayGrid[8][12] = formDisplayCell;
		formDisplayCell = new FormEmptyCell();
		formDisplayCell.setColumn(13);
		formDisplayCell.setColumnSpan(1);
		formDisplayCell.setRow(8);
		formDisplayCell.setRowSpan(1);
		formDisplayCell.setCellType(CellType.CALC);
		formDisplayGrid[8][13] = formDisplayCell;
		formDisplayCell = new FormEmptyCell();
		formDisplayCell.setColumn(0);
		formDisplayCell.setColumnSpan(1);
		formDisplayCell.setRow(9);
		formDisplayCell.setRowSpan(1);
		formDisplayCell.setCellType(CellType.ROW_HEADING);
		formDisplayGrid[9][0] = formDisplayCell;
		formDisplayCell = new FormEmptyCell();
		formDisplayCell.setColumn(1);
		formDisplayCell.setColumnSpan(1);
		formDisplayCell.setRow(9);
		formDisplayCell.setRowSpan(1);
		formDisplayCell.setCellType(CellType.ROW_HEADING);
		formDisplayGrid[9][1] = formDisplayCell;
		formDisplayCell = new FormEmptyCell();
		formDisplayCell.setColumn(2);
		formDisplayCell.setColumnSpan(1);
		formDisplayCell.setRow(9);
		formDisplayCell.setRowSpan(1);
		formDisplayCell.setCellType(CellType.ROW_HEADING);
		formDisplayGrid[9][2] = formDisplayCell;
		formDisplayCell = new FormEmptyCell();
		formDisplayCell.setColumn(3);
		formDisplayCell.setColumnSpan(1);
		formDisplayCell.setRow(9);
		formDisplayCell.setRowSpan(1);
		formDisplayCell.setCellType(CellType.INPUT);
		formDisplayGrid[9][3] = formDisplayCell;
		formDisplayCell = new FormEmptyCell();
		formDisplayCell.setColumn(4);
		formDisplayCell.setColumnSpan(1);
		formDisplayCell.setRow(9);
		formDisplayCell.setRowSpan(1);
		formDisplayCell.setCellType(CellType.INPUT);
		formDisplayGrid[9][4] = formDisplayCell;
		formDisplayCell = new FormEmptyCell();
		formDisplayCell.setColumn(5);
		formDisplayCell.setColumnSpan(1);
		formDisplayCell.setRow(9);
		formDisplayCell.setRowSpan(1);
		formDisplayCell.setCellType(CellType.INPUT);
		formDisplayGrid[9][5] = formDisplayCell;
		formDisplayCell = new FormEmptyCell();
		formDisplayCell.setColumn(6);
		formDisplayCell.setColumnSpan(1);
		formDisplayCell.setRow(9);
		formDisplayCell.setRowSpan(1);
		formDisplayCell.setCellType(CellType.INPUT);
		formDisplayGrid[9][6] = formDisplayCell;
		formDisplayCell = new FormEmptyCell();
		formDisplayCell.setColumn(7);
		formDisplayCell.setColumnSpan(1);
		formDisplayCell.setRow(9);
		formDisplayCell.setRowSpan(1);
		formDisplayCell.setCellType(CellType.CALC);
		formDisplayGrid[9][7] = formDisplayCell;
		formDisplayCell = new FormEmptyCell();
		formDisplayCell.setColumn(8);
		formDisplayCell.setColumnSpan(1);
		formDisplayCell.setRow(9);
		formDisplayCell.setRowSpan(1);
		formDisplayCell.setCellType(CellType.INPUT);
		formDisplayGrid[9][8] = formDisplayCell;
		formDisplayCell = new FormEmptyCell();
		formDisplayCell.setColumn(9);
		formDisplayCell.setColumnSpan(1);
		formDisplayCell.setRow(9);
		formDisplayCell.setRowSpan(1);
		formDisplayCell.setCellType(CellType.INPUT);
		formDisplayGrid[9][9] = formDisplayCell;
		formDisplayCell = new FormEmptyCell();
		formDisplayCell.setColumn(10);
		formDisplayCell.setColumnSpan(1);
		formDisplayCell.setRow(9);
		formDisplayCell.setRowSpan(1);
		formDisplayCell.setCellType(CellType.INPUT);
		formDisplayGrid[9][10] = formDisplayCell;
		formDisplayCell = new FormEmptyCell();
		formDisplayCell.setColumn(11);
		formDisplayCell.setColumnSpan(1);
		formDisplayCell.setRow(9);
		formDisplayCell.setRowSpan(1);
		formDisplayCell.setCellType(CellType.INPUT);
		formDisplayGrid[9][11] = formDisplayCell;
		formDisplayCell = new FormEmptyCell();
		formDisplayCell.setColumn(0);
		formDisplayCell.setColumnSpan(0);
		formDisplayCell.setRow(0);
		formDisplayCell.setRowSpan(0);
		formDisplayCell.setCellType(CellType.EMPTY);
		formDisplayGrid[9][12] = formDisplayCell;
		formDisplayCell = new FormEmptyCell();
		formDisplayCell.setColumn(13);
		formDisplayCell.setColumnSpan(1);
		formDisplayCell.setRow(9);
		formDisplayCell.setRowSpan(1);
		formDisplayCell.setCellType(CellType.CALC);
		formDisplayGrid[9][13] = formDisplayCell;
		formDisplayCell = new FormEmptyCell();
		formDisplayCell.setColumn(0);
		formDisplayCell.setColumnSpan(1);
		formDisplayCell.setRow(10);
		formDisplayCell.setRowSpan(1);
		formDisplayCell.setCellType(CellType.ROW_HEADING);
		formDisplayGrid[10][0] = formDisplayCell;
		formDisplayCell = new FormEmptyCell();
		formDisplayCell.setColumn(1);
		formDisplayCell.setColumnSpan(1);
		formDisplayCell.setRow(10);
		formDisplayCell.setRowSpan(1);
		formDisplayCell.setCellType(CellType.ROW_HEADING);
		formDisplayGrid[10][1] = formDisplayCell;
		formDisplayCell = new FormEmptyCell();
		formDisplayCell.setColumn(2);
		formDisplayCell.setColumnSpan(1);
		formDisplayCell.setRow(10);
		formDisplayCell.setRowSpan(1);
		formDisplayCell.setCellType(CellType.ROW_HEADING);
		formDisplayGrid[10][2] = formDisplayCell;
		formDisplayCell = new FormEmptyCell();
		formDisplayCell.setColumn(3);
		formDisplayCell.setColumnSpan(1);
		formDisplayCell.setRow(10);
		formDisplayCell.setRowSpan(1);
		formDisplayCell.setCellType(CellType.CALC);
		formDisplayGrid[10][3] = formDisplayCell;
		formDisplayCell = new FormEmptyCell();
		formDisplayCell.setColumn(4);
		formDisplayCell.setColumnSpan(1);
		formDisplayCell.setRow(10);
		formDisplayCell.setRowSpan(1);
		formDisplayCell.setCellType(CellType.CALC);
		formDisplayGrid[10][4] = formDisplayCell;
		formDisplayCell = new FormEmptyCell();
		formDisplayCell.setColumn(5);
		formDisplayCell.setColumnSpan(1);
		formDisplayCell.setRow(10);
		formDisplayCell.setRowSpan(1);
		formDisplayCell.setCellType(CellType.CALC);
		formDisplayGrid[10][5] = formDisplayCell;
		formDisplayCell = new FormEmptyCell();
		formDisplayCell.setColumn(6);
		formDisplayCell.setColumnSpan(1);
		formDisplayCell.setRow(10);
		formDisplayCell.setRowSpan(1);
		formDisplayCell.setCellType(CellType.CALC);
		formDisplayGrid[10][6] = formDisplayCell;
		formDisplayCell = new FormEmptyCell();
		formDisplayCell.setColumn(7);
		formDisplayCell.setColumnSpan(1);
		formDisplayCell.setRow(10);
		formDisplayCell.setRowSpan(1);
		formDisplayCell.setCellType(CellType.CALC);
		formDisplayGrid[10][7] = formDisplayCell;
		formDisplayCell = new FormEmptyCell();
		formDisplayCell.setColumn(8);
		formDisplayCell.setColumnSpan(1);
		formDisplayCell.setRow(10);
		formDisplayCell.setRowSpan(1);
		formDisplayCell.setCellType(CellType.CALC);
		formDisplayGrid[10][8] = formDisplayCell;
		formDisplayCell = new FormEmptyCell();
		formDisplayCell.setColumn(9);
		formDisplayCell.setColumnSpan(1);
		formDisplayCell.setRow(10);
		formDisplayCell.setRowSpan(1);
		formDisplayCell.setCellType(CellType.CALC);
		formDisplayGrid[10][9] = formDisplayCell;
		formDisplayCell = new FormEmptyCell();
		formDisplayCell.setColumn(10);
		formDisplayCell.setColumnSpan(1);
		formDisplayCell.setRow(10);
		formDisplayCell.setRowSpan(1);
		formDisplayCell.setCellType(CellType.CALC);
		formDisplayGrid[10][10] = formDisplayCell;
		formDisplayCell = new FormEmptyCell();
		formDisplayCell.setColumn(11);
		formDisplayCell.setColumnSpan(1);
		formDisplayCell.setRow(10);
		formDisplayCell.setRowSpan(1);
		formDisplayCell.setCellType(CellType.CALC);
		formDisplayGrid[10][11] = formDisplayCell;
		formDisplayCell = new FormEmptyCell();
		formDisplayCell.setColumn(12);
		formDisplayCell.setColumnSpan(1);
		formDisplayCell.setRow(10);
		formDisplayCell.setRowSpan(1);
		formDisplayCell.setCellType(CellType.CALC);
		formDisplayGrid[10][12] = formDisplayCell;
		formDisplayCell = new FormEmptyCell();
		formDisplayCell.setColumn(0);
		formDisplayCell.setColumnSpan(0);
		formDisplayCell.setRow(0);
		formDisplayCell.setRowSpan(0);
		formDisplayCell.setCellType(CellType.EMPTY);
		formDisplayGrid[10][13] = formDisplayCell;

		return formDisplayGrid;
	}



}

